### ISSUE TITLE
new version of globus_idk is creating crontab errors

### ISSUE THREAD

**Issue by lisagoodrich** [NCAR/GlobusArchiver#51]
There was a recent update of the globus_jdk on minivet-vm and the Kuwait archivers started giving crontab errors.  It appears the data is archiving but no confirmation emails are being sent.  The only email is a crontab failure email.

Here is the current  version on minivet-vm:
/usr/local/anaconda3/bin/python3 -c "import globus_sdk; print(globus_sdk.__version__)"
3.5.0

Per Jeff Hancock here is the version on, delphi19:
/usr/local/anaconda3/bin/python3 -c "import globus_sdk; print(globus_sdk.__version__)"
1.8.0

For V2 doc, I was looking at: https://globus-sdk-python.readthedocs.io/en/2.x-line/clients/transfer.html#globus_sdk.TransferClient.task_event_list

Per Paul Prestopnik: I will need to find some way to test these changes.  Probably what I will do is create a branch for GlobusArchiver, make some changes and have you install from the branch.

**Comment by jeffhancockNCAR** [comment]
Just to add to that, the issue is with line 1103 trying to use the named parameter "filter" in the task_event_list call.  That named parameter no longer exists, apparently from V2 on.
